from functools import lru_cache

from pydantic import SecretStr
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    app_name: str = "MAnalyzer – Medical Report Analyzer"
    debug: bool = False

    openai_api_key: SecretStr = SecretStr("")
    anthropic_api_key: SecretStr = SecretStr("")
    default_llm_provider: str = "openai"

    max_upload_size_mb: int = 20
    allowed_extensions: list[str] = [".pdf", ".csv", ".json", ".txt"]
    supported_report_types: list[str] = ["lab", "radiology", "pathology", "general"]

    disclaimer_enabled: bool = True
    medical_disclaimer: str = (
        "This analysis is generated by AI and is NOT a substitute for "
        "professional medical advice, diagnosis, or treatment. Always consult "
        "a qualified healthcare provider for medical decisions."
    )

    context_max_records: int = 200

    allowed_origins: str = "*"
    api_key: SecretStr = SecretStr("")
    rate_limit: str = "30/minute"
    encryption_key: SecretStr = SecretStr("")

    session_ttl_minutes: int = 60

    model_config = {"env_file": ".env", "env_file_encoding": "utf-8"}

    @property
    def cors_origins(self) -> list[str]:
        if self.allowed_origins.strip() == "*":
            return ["*"]
        return [o.strip() for o in self.allowed_origins.split(",") if o.strip()]

    @property
    def auth_enabled(self) -> bool:
        return len(self.api_key.get_secret_value()) > 0


@lru_cache
def get_settings() -> Settings:
    return Settings()
